### ISSUE TITLE
[Bug]: Given block <BLOCK> is not a lockable block/tile entity

### ISSUE THREAD

**Issue by KaidenMikami** [spnda/BlockProt#118]
### Version of BlockProt

BlockProt v1.0.2 - git-Paper-68 (MC: 1.18.1)

### Description of the bug

Had a world created, and decided to disable the locks on the furnace and now everytime a player uses the furnace, it prints out a huge error on the console.

### Steps to reproduce

1. Create World
2. Remove furnaces from lockable blocks
3. Open furnace

### Additional context

Log for the error:
```
Could not pass event InventoryOpenEvent to BlockProt v1.0.2
java.lang.RuntimeException: Given block FURNACE is not a lockable block/tile entity
        at de.sean.blockprot.bukkit.nbt.BlockNBTHandler.<init>(BlockNBTHandler.java:81) ~[blockprot-spigot-1.0.2-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryOpen(InventoryEventListener.java:144) ~[blockprot-spigot-1.0.2-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1324) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1493) ~[?:?]
        at net.minecraft.world.level.block.FurnaceBlock.openContainer(FurnaceBlock.java:41) ~[?:?]
        at net.minecraft.world.level.block.AbstractFurnaceBlock.use(AbstractFurnaceBlock.java:44) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:978) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:584) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1821) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by KaidenMikami** [comment]
This is not entirely fixed. For player interactions? Yes, but hoppers still gives the error.

Log:
```
[03:07:07 ERROR]: Could not pass event InventoryMoveItemEvent to BlockProt v1.0.3
java.lang.RuntimeException: Given block FURNACE is not a lockable block/tile entity
        at de.sean.blockprot.bukkit.nbt.BlockNBTHandler.<init>(BlockNBTHandler.java:82) ~[blockprot-spigot-1.0.3-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.HopperEventListener.onItemMove(HopperEventListener.java:43) ~[blockprot-spigot-1.0.3-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.callPullMoveEvent(HopperBlockEntity.java:308) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPull(HopperBlockEntity.java:248) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$suckInItems$3(HopperBlockEntity.java:461) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.anyMatch(HopperBlockEntity.java:432) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.suckInItems(HopperBlockEntity.java:458) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$pushItemsTick$0(HopperBlockEntity.java:141) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:163) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:140) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1167) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1119) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:956) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:679) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by spnda** [comment]
@KaidenMikami Thanks for reporting this. I've also fixed this for hoppers now.
