### ISSUE TITLE
[Bug]: Could not pass event InventoryMoveItemEvent to BlockProt v1.0.4

### ISSUE THREAD

**Issue by taka1945** [spnda/BlockProt#131]
### Version of BlockProt

BlockProt v1.0.4 / paper-api-1.18.1

### Description of the bug

[12:47:59 ERROR]: Could not pass event InventoryMoveItemEvent to BlockProt v1.0.4
java.lang.RuntimeException: Given block DROPPER is not a lockable block/tile entity
        at de.sean.blockprot.bukkit.nbt.BlockNBTHandler.<init>(BlockNBTHandler.java:82) ~[blockprot-spigot-1.0.4-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.HopperEventListener.onItemMove(HopperEventListener.java:54) ~[blockprot-spigot-1.0.4-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor557.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-136]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:285) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:214) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:356) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:159) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:140) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1167) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1119) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:956) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:679) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-136]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-136]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

### Steps to reproduce

just found those error logs.

**Comment by spnda** [comment]
I already have a fix for this which I am probably pushing soon but I am investigating a issue with Paper right now in connection with this issue that lets items disappear.

**Comment by Gabriel-Sohn** [comment]
Version of BlockProt
BlockProt v1.0.4 / paper-api-1.18.1
Description of the bug
![image](https://user-images.githubusercontent.com/55875014/149050869-669ce5ba-b269-4707-8b5e-8f15248b728a.png)

Disabled protection with all storage devices that allowed resource movement/conversion furnaces, hoppers, etc. Did a live reload and it stop. The number of errors generated appeared to be related with automatic furnaces so I had to disable the protection feature.

**Comment by spnda** [comment]
> I already have a fix for this which I am probably pushing soon but I am investigating a issue with Paper right now in connection with this issue that lets items disappear.

The bug with Spigot seems to have been fixed recently. I urge everyone to upgrade to Paper#141 or a recent/new build of Spigot.
