### ISSUE TITLE
[Bug]: 1.19.1 Use error

### ISSUE THREAD

**Issue by airskyblue** [spnda/BlockProt#172]
### Version of BlockProt

blockprot-spigot-1.1.3-all.jar/Paper 1.19.1

### Description of the bug

After updating version 1.19.1, this problem will occur in the use of plug-ins, which cannot be used

### Steps to reproduce

You can update 1.19.1 and try to use the plug-in

### Additional context

[20:13:37 ERROR]: Could not pass event InventoryClickEvent to BlockProt v1.1.3
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
        at de.sean.blockprot.bukkit.shaded.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:89) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:81) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:176) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:164) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.inventories.FriendSearchInventory.openAnvilInventory(FriendSearchInventory.java:37) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.inventories.FriendManageInventory.onClick(FriendManageInventory.java:125) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryClick(InventoryEventListener.java:60) ~[blockprot-spigot-1.1.3-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-87]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3252) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-87]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

null
org.bukkit.command.CommandException: Unhandled exception executing command 'blockprot' in plugin BlockProt v1.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.1.jar:git-Paper-87]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59) ~[paper-1.19.1.jar:git-Paper-87]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:290) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2257) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2222) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-87]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-87]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at de.sean.blockprot.bukkit.commands.DebugCommand.onCommand(DebugCommand.java:37) ~[blockprot-spigot-1.1.3-all.jar:?]
        at de.sean.blockprot.bukkit.commands.BlockProtCommand.onCommand(BlockProtCommand.java:51) ~[blockprot-spigot-1.1.3-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by spnda** [comment]
Thanks for bringing this to my attention. I am fixing this right now and will update the plugin to 1.1.4 soon.

**Comment by spnda** [comment]
I have opened https://github.com/WesJD/AnvilGUI/pull/222, when that's merged I can release 1.1.4 and close this issue.

Fixed by https://github.com/WesJD/AnvilGUI/pull/222.
