### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ilfarpro** [spnda/BlockProt#176]
### Version of BlockProt

1.1.4 Purpur-1759 build

### Description of the bug

```
- [Wed 13:05:30 ERROR Minecraft] Could not pass event InventoryClickEvent to BlockProt v1.1.4
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:98)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:91)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:176)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:164)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.inventories.FriendSearchInventory.openAnvilInventory(FriendSearchInventory.java:37)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.inventories.FriendManageInventory.onClick(FriendManageInventory.java:125)
    at blockprot-spigot-1.1.4-all.jar//de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryClick(InventoryEventListener.java:60)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor73.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3400)
    at net.minecraft.network.protocol
```

### Steps to reproduce

Can't reproduce, because it was caused by players I can not contact to get information

**Comment by spnda** [comment]
Ah, you're on 1.19.2 I guess? Gonna update to 1.19.2 in a second.

**Comment by spnda** [comment]
I've updated to 1.19.2 with BlockProt 1.1.5. https://github.com/spnda/BlockProt/releases/tag/1.1.5
