### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ilfarpro** [spnda/BlockProt#180]
### Version of BlockProt

1.1.5 

### Description of the bug

Getting Exception in console, have no infromation what was going on this moment

### Steps to reproduce

N/A

### Additional context

```
[10:06:52] [Server thread/WARN]: [BlockProt] Task #5705405 for BlockProt v1.1.5 generated an exception
de.sean.blockprot.bukkit.shaded.nbtapi.NbtApiException: [?]Exception while getting NBTCompound from TileEntity!
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(NBTReflectionUtil.java:247) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTTileEntity.getCompound(NBTTileEntity.java:38) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTCompound.getCompound(NBTCompound.java:63) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:604) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.nbt.BlockNBTHandler.setName(BlockNBTHandler.java:162) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.listeners.BlockEventListener.lambda$onBlockPlace$1(BlockEventListener.java:188) ~[blockprot-spigot-1.1.5-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1832]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "target" is null
	at de.sean.blockprot.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:185) ~[blockprot-spigot-1.1.5-all.jar:?]
	at de.sean.blockprot.bukkit.shaded.nbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(NBTReflectionUtil.java:237) ~[blockprot-spigot-1.1.5-all.jar:?]
	... 14 more
```

**Comment by spnda** [comment]
Only reason this should ever happen if the block is placed and destroyed the next tick. Will try to add some check to prevent this from happening.

**Comment by ilfarpro** [comment]
Thank you!
