### ISSUE TITLE
[Bug]: Minecraft 1.19.4 - BlockProt is working just partially

### ISSUE THREAD

**Issue by nyomen** [spnda/BlockProt#206]
### Version of BlockProt

1.1.8

### Description of the bug

Hi there, we just updated our minecraftserver to 1.19.4 and there is in issue with the BlockProt plugin.

### Steps to reproduce

Click Search Players.
![grafik](https://user-images.githubusercontent.com/46107963/227569875-7847b484-0029-42a0-bfed-bb7c7d07c593.png)

Server sends that meassage
```
[15:27:18 ERROR]: Could not pass event InventoryClickEvent to BlockProt v1.1.8
java.lang.NoClassDefFoundError: Could not initialize class de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI
        at de.sean.blockprot.bukkit.shaded.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:555) ~[blockprot-spigot-1.1.8-all.jar:?]
        at de.sean.blockprot.bukkit.inventories.BlockLockInventory.onClick(BlockLockInventory.java:121) ~[blockprot-spigot-1.1.8-all.jar:?]
        at de.sean.blockprot.bukkit.listeners.InventoryEventListener.onInventoryClick(InventoryEventListener.java:61) ~[blockprot-spigot-1.1.8-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-451]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-451]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-451]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3179) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-451]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by spnda** [comment]
Thanks for the report. AnvilGUI has already been updated accordingly, will release a new version tomorrow.
